name: Rust
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
env:
  CARGO_TERM_COLOR: always
  PROJECT_NAME: test_generated_project
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Generate a new project from template
      - uses: cargo-generate/cargo-generate-action@latest
        with:
          name: ${{ env.PROJECT_NAME }}
      # Set up Rust toolchain for the generated project
      - uses: dtolnay/rust-toolchain@stable
      # Move generated project out of template dir to avoid conflicts
      - name: Move generated project
        run: |
          mv $PROJECT_NAME ${{ runner.temp }}/
          cd ${{ runner.temp }}/$PROJECT_NAME
          cargo build --verbose
          cargo run --verbose
